[16.0][MIG] stock_request_kanban: Migration to 16.0
OCA/stock-logistics-request pull request #44
Opened 2024-10-02 00:25 UTC by matt454357

Migrated from 15.0, from old repository at https://github.com/OCA/stock-logistics-warehouse

2024-10-02 16:46 UTC, matt454357 commented
@rousseldenis Can this PR supersede #8?

2025-01-01 20:45 UTC, matt454357 commented
Hi @LoisRForgeFlow, Do you have someone there that would be interested in reviewing this PR?

2025-02-14 13:13 UTC, etobella commented
Why are you superseeding. You did not ask for changes on the previous PR

2025-03-04 09:26 UTC, etobella approved these changes
Technical review :+1: 

I will accept the superseed because the previous PR was failing

/ocabot migration stock_request_kanban

2025-03-04 09:42 UTC, etobella requested changes
Javascript has not been migrated. IT is raising failures.... If it is a problem for you, we can make the changes.

2025-07-09 23:13 UTC, matt454357 commented
@etobella I believe the JavaScript issue is fixed.  Would you like to review this again?

2025-07-10 04:34 UTC, etobella approved these changes

2025-07-10 07:34 UTC, LoisRForgeFlow approved these changes
/ocabot merge nobump

2025-07-10 07:40 UTC, merged