[18.0][MIG] stock_request: Migration to 18.0
OCA/stock-logistics-request pull request #48
Opened 2024-10-25 21:29 UTC by ced-adhoc

2024-10-26 11:54 UTC, rousseldenis commented
/ocabot migration stock_request

2024-10-26 11:55 UTC, rousseldenis commented
@ced-adhoc Thanks for this. Could you check tests?

2024-10-28 13:52 UTC, ced-adhoc commented
@rousseldenis Sure! I'm on it! I'm also running into an issue with the view_stock_request_form -it's not displaying correctly at lower zoom levels, and I might need help figuring that part out. I'll let you know when it's done, ASAP.

2024-11-01 15:31 UTC, mav-adhoc approved these changes

2024-11-04 17:58 UTC, luc-adhoc approved these changes
functional review

2024-11-04 19:35 UTC, mav-adhoc commented
LGTM!

2024-11-05 11:38 UTC, LoisRForgeFlow requested changes
Stock request orders view is broken. From runbot:

![image](https://github.com/user-attachments/assets/2a6b71f6-6191-4c9e-9c3e-8111543a8983)

could you have a look?

could you also cherry pick this recent commit https://github.com/OCA/stock-logistics-request/pull/50/commits/fa69ab4441560661ce9b49f839b00cf15eca83ad

Thanks!

2024-11-08 08:43 UTC, LoisRForgeFlow requested changes
@ced-adhoc Thanks for attending my comments!

One more detail, the messages posted in the chatter of the stock request are not parsed as html:

![image](https://github.com/user-attachments/assets/dec289d6-78c2-4cd1-a411-0f1b3aac292e)

Could you have a look?

2024-11-11 07:30 UTC, LoisRForgeFlow requested changes
Thanks for fixing! However it seems that now https://github.com/OCA/stock-logistics-request/commit/fa69ab4441560661ce9b49f839b00cf15eca83ad got removed, could you add it again? Also, CI is red.

2024-11-11 20:00 UTC, ced-adhoc commented
Hi @LoisRForgeFlow !  Yes, no worries, I'll cherry-pick your commit once my job is done. The CI error was due to somewarnings related to the html message. Please let me know if you have further observations :)

2024-11-12 08:06 UTC, LoisRForgeFlow commented
@ced-adhoc Thanks! just let me know when ready to review again, it looks like we are almost there.

2024-11-12 08:15 UTC, rousseldenis commented on stock_request/models/stock_move_line.py
> +            )
@ced-adhoc You should use translation function arguments to pass translation value. `_("%(request_name)s", message_data)`

2024-11-12 20:34 UTC, ced-adhoc commented
Hi @LoisRForgeFlow , just checking if I need to reorder the commits so your UPD commit comes before my MIG commit. 

@rousseldenis I believe is now aligned with your request.

2024-11-13 08:07 UTC, rousseldenis commented on stock_request/models/stock_move_line.py
> +        # _("%(request_name)s", message_data)
Please remove this

2024-11-13 08:08 UTC, rousseldenis commented on stock_request/models/stock_move_line.py
> +            "<ul><li><b>%(product_name)s</b>: Transferred quantity %(product_qty)s "
Why not using translation here ?

2024-11-13 14:20 UTC, ced-adhoc commented on stock_request/models/stock_move_line.py
> +            "<ul><li><b>%(product_name)s</b>: Transferred quantity %(product_qty)s "
Because I missed it by mistake.

2024-11-13 15:03 UTC, LoisRForgeFlow approved these changes
All Good now, thanks :smile:

2024-11-13 15:03 UTC, LoisRForgeFlow commented
@rousseldenis good from your side too?

2024-11-13 16:01 UTC, rousseldenis approved these changes

2024-11-13 16:02 UTC, rousseldenis commented
/ocabot merge nobump

2024-11-13 16:06 UTC, merged